added gui on vagrant box
docker-scripts/dev--LTSP pull request #65
Opened 2018-06-27 15:16 UTC by d78ui98

2018-06-27 15:54 UTC, dashohoxha commented on install.sh
> +startxfce4&
You should install `xubuntu-desktop`

2018-06-27 18:15 UTC, d78ui98 commented on install.sh
> +startxfce4&
sure.

2018-06-27 20:42 UTC, dashohoxha requested changes
I don't see the GUI added here.

2018-06-27 20:47 UTC, d78ui98 commented
please check here - https://github.com/docker-scripts/dev--LTSP/pull/65/commits/445a872f786594a020968b7ff1c235ea820e228b
Now that we are installing one package, I thought I will is better to add along with all the other installing packages.

2018-06-28 03:00 UTC, dashohoxha approved these changes
It seems Ok.

2018-06-28 04:12 UTC, akash0x53 approved these changes

2018-06-28 08:09 UTC, merged